# Generated by Django 5.2.4 on 2025-07-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questtion_text',
            new_name='question_text',
        ),
    ]
